### PR TITLE
Fixed typos & experimental read support for MS Project Database (.mdp) files

### PR DESCRIPTION
**Pull request by tangervu**
I managed to add support for mdp files using mdbtools command line tools. Not pretty implementation which works only on Linux, but it's the best that I could come with.

### CODE REVIEW

**Comment by Progi1984** [comment]
Good job for this pull request.

Some questions :
- Could you add some samples files ?
- The extension is not MPD ? (like there : http://office.microsoft.com/en-us/project-help/file-formats-supported-by-microsoft-office-project-HA010140395.aspx)
- Do you use externals tools like MDB Tools ?
  The goal of PHPOffice is to permit to access files like MS Project, Excel or Word just in PHP without externals tools. It's why we read binary files for Excel 97 in PHPExcel or write text files for RTF in PHPWord.

**Comment by tangervu** [comment]
Yes, i use MDB command line tools in the PHP class. I agree that it's 
not a pretty approach, but as far as I know there isn't any good 
platform independent solution to read Access Databases available (which 
MPD is).

And yes, I wrote incorrectly MDP in the previous message, MPD is the 
right extension.

A sample file is included as attachment (created in a MS Project 
compatible application)

**Comment by Progi1984** [comment]
The only good solution would be to find a doc on MDB binary file format and write a reader for MS Access files. And why not create a PHPAccess library in @PHPOffice ?
If you find documentation, I would be interesting on working on it.

This solution would permit to have a code platform dependant. For PHPProject, that would ask just a dependency in PHPAccess.

**Comment by tangervu** [comment]
Didn't find any docs about MS Access, I believe it's not available from 
Microsoft. However you can access those via ODBC in Windows and also 
unixODBC in Linux (which is hardcoded system wide into a single file). 
Anyways the MPD file format is already deprecated so I don't have much 
interest on putting much more effort since I now have a good enough 
reader for the format for my own use.

In case you are interested, I also created reader/writer for the MS 
Project XML format.

**Comment by Progi1984** [comment]
Ok... If i find any documentation on MDB file format, i will work on a clean reader.

And your reader/writer for MS Project XML is clean ?

**Comment by tangervu** [comment]
Yep, it's based on XMLWriter. Check out 
https://github.com/tangervu/PHPProject/blob/develop/Classes/PHPProject/Writer/MSProjectXML.php 
for the first commits.

However have to mention that I needed to reconstruct the whole 
PHPProject for my own needs since it was lacking for example calendars. 
Plus the code is still quite immature, I will still work on it later on.

**Pull request closed without merging**
